---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  labels:
    "personal_project": web-app
type: Opaque
# echo -n test123 | base64
# echo dGVzdDEyMw== | base64 --decode
data:
  root_pass: dGVzdDEyMw== #test123
  user: dGVzdF91c2Vy #test_user
  password: dGVzdA== #test