---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
    "personal_project": web-app
type: Opaque
# echo -n test123 | base64
# echo dGVzdDEyMw== | base64 --decode
data:
  root_pass: dGVzdDEyMw== #test123
  user: dGVzdF91c2Vy #test_user
  password: dGVzdA== #test
  tls.crt: <BASE64_ENCRYPTED_CRT_FILE>
  tls.key: <BASE64_ENCRYPTED_KEY_FILE>